---

- name: install httpd package
  yum:
    name: httpd
    state: latest

#- name: install service package
  #yum:
    #name: service
    #state: latest

- name: put index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: start httpd
  service:
    name: httpd
    state: started
    enabled: yes
#- name: start service
  #service:
    #name: service
    #state: started
    #enabled: yes

